import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@/provider/theme-provider'
import ModalProvider from '@/provider/modal-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/lxgw-wenkai-webfont/1.7.0/lxgwwenkai-regular.min.css"
        />
      </head>
      <body className={`antialiased bg-black text-white font-wenkai`}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          {children}
          <ModalProvider />
        </ThemeProvider>
      </body>
    </html>
  )
}
